esphome:
  name: esp01test2
  friendly_name: esp01test2

esp8266:
  board: esp01
  framework: 
    version: "recommended"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "vsA8KO1JAdcYF2XRFcEro+oWIYaludKWgY8w7J28b2c="

ota:
  - platform: esphome
    password: "8e8ceca3627b8146614e4da1d4c92c8f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails

web_server:
  port: 80