esphome:
  name: esp01test3
  friendly_name: esp01test3

esp8266:
  board: esp01

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "mXsT+1PShexeikfHmQCOIMK344IXuoXB6pX3pv8u19s="

#ota:
#  - platform: esphome
#    password: "6cbe0b5c2ca2859087575f185590c5cb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails

web_server:

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    update_interval: 15s