esphome:
  name: nodemcu-pp-test-1
  friendly_name: nodemcu_pp_test_1

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "oLuVcUcL84T7P44uqcZdACYbFCrKL9Sts8JsPnyWF6E="

ota:
  - platform: esphome
    password: "23bc76a5d56ca1233df03b0b94a098aa"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcu-Pp-Test-1"
    password: "Z9jMm0WA2diK"

captive_portal:
    
web_server:

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    update_interval: 1s

deep_sleep:
  id: deep_sleep_1
  run_duration: 10s
  sleep_duration: 30s
