esphome:
  name: wemosd1-test1
  friendly_name: wemosd1_test1

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "aF0wvb1iHlHfoDhwbayAJz0eu97XjqTWxRtHbUdPt9c="

ota:
  - platform: esphome
    password: "e4be30903fd7b98ce6e9ed4166262425"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemosd1-Test1 Fallback Hotspot"
    password: "8vgoF1jE8gPM"

captive_portal:

web_server:

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    update_interval: 1s

deep_sleep:
  id: deep_sleep_1
  run_duration: 10s
  sleep_duration: 30s
